import type { Locale, ServiceKey, ServicePageData, ServiceSummary, ToolItem } from "@/src/types";

const toolLogos: Record<string, ToolItem> = {
  "Google Search Console": {
    name: "Google Search Console",
    logo: "/images/tools/google-search-console.svg",
    alt: "Google Search Console logo",
  },
  "Google Analytics 4": {
    name: "Google Analytics 4",
    logo: "/images/tools/google-analytics.svg",
    alt: "Google Analytics 4 logo",
  },
  Ahrefs: { name: "Ahrefs", logo: "/images/tools/ahrefs.png", alt: "Ahrefs logo" },
  Semrush: { name: "Semrush", logo: "/images/tools/semrush.svg", alt: "Semrush logo" },
  "Screaming Frog": {
    name: "Screaming Frog",
    logo: "/images/tools/screaming-frog.svg",
    alt: "Screaming Frog logo",
  },
  ChatGPT: { name: "ChatGPT", logo: "/images/tools/chatgpt.svg", alt: "ChatGPT logo" },
  Claude: { name: "Claude", logo: "/images/tools/claude.png", alt: "Claude logo" },
  Gemini: { name: "Gemini", logo: "/images/tools/gemini.png", alt: "Google Gemini logo" },
  "Google Trends": {
    name: "Google Trends",
    logo: "/images/tools/google-trends.png",
    alt: "Google Trends logo",
  },
  BigQuery: { name: "BigQuery", logo: "/images/tools/bigquery.png", alt: "Google BigQuery logo" },
  Python: { name: "Python", logo: "/images/tools/python.png", alt: "Python logo" },
  "OpenAI API": { name: "OpenAI API", logo: "/images/tools/openai.svg", alt: "OpenAI API logo" },
  "Custom API Integrations": {
    name: "Custom API Integrations",
    logo: "/images/tools/custom-api.png",
    alt: "Custom API integrations icon",
  },
  "Looker Studio": {
    name: "Looker Studio",
    logo: "/images/tools/looker-studio.png",
    alt: "Looker Studio logo",
  },
  "Power BI": { name: "Power BI", logo: "/images/tools/power-bi.png", alt: "Microsoft Power BI logo" },
  SQL: { name: "SQL", logo: "/images/tools/sql.png", alt: "SQL logo" },
  "Google Analytics": {
    name: "Google Analytics",
    logo: "/images/tools/google-analytics.svg",
    alt: "Google Analytics logo",
  },
  "Google Sheets": {
    name: "Google Sheets",
    logo: "/images/tools/google-sheets.png",
    alt: "Google Sheets logo",
  },
  JavaScript: { name: "JavaScript", logo: "/images/tools/javascript.png", alt: "JavaScript logo" },
  "REST APIs": { name: "REST APIs", logo: "/images/tools/rest-api.png", alt: "REST API logo" },
  Docker: { name: "Docker", logo: "/images/tools/docker.png", alt: "Docker logo" },
  GitHub: { name: "GitHub", logo: "/images/tools/github.png", alt: "GitHub logo" },
  AWS: { name: "AWS", logo: "/images/tools/aws.png", alt: "Amazon Web Services logo" },
  "Google Cloud": {
    name: "Google Cloud",
    logo: "/images/tools/google-cloud.png",
    alt: "Google Cloud logo",
  },
};

const toolList = (names: string[]) => names.map((name) => toolLogos[name]);

export const serviceSummaries: Record<Locale, ServiceSummary[]> = {
  en: [
    {
      key: "aiSeo",
      title: "AI SEO",
      eyebrow: "Search visibility",
      description:
        "Get found on Google, ChatGPT and Gemini with technical SEO, intent research and AI-search visibility planning.",
      benefits: ["Search intent mapping", "AI visibility", "Technical audits"],
      href: "/ai-seo-2/",
    },
    {
      key: "automation",
      title: "Automation",
      eyebrow: "Smarter workflows",
      description:
        "Remove repetitive marketing tasks with AI-assisted content, competitor checks, chatbot replies and workflow automations.",
      benefits: ["Content workflows", "API connections", "Human review loops"],
      href: "/automation/",
    },
    {
      key: "reporting",
      title: "Reporting",
      eyebrow: "Clear analytics",
      description:
        "Bring marketing, SEO and sales numbers into one readable dashboard that updates automatically and supports decisions.",
      benefits: ["KPI dashboards", "GA4 & GSC", "Executive summaries"],
      href: "/report/",
    },
    {
      key: "toolGeneration",
      title: "Tool Generation",
      eyebrow: "Custom systems",
      description:
        "Build custom SEO tools, internal dashboards and data utilities when off-the-shelf software does not fit.",
      benefits: ["Custom scripts", "Internal tools", "Cloud integrations"],
      href: "/tool-generation/",
    },
  ],
  el: [
    {
      key: "aiSeo",
      title: "AI SEO",
      eyebrow: "Ορατότητα αναζήτησης",
      description:
        "Να σας βρίσκουν σε Google, ChatGPT και Gemini με τεχνικό SEO, ανάλυση πρόθεσης και στρατηγική AI-search προβολής.",
      benefits: ["Χαρτογράφηση πρόθεσης", "AI visibility", "Τεχνικοί έλεγχοι"],
      href: "/el/ai-seo-4/",
    },
    {
      key: "automation",
      title: "Αυτοματισμοί",
      eyebrow: "Πιο έξυπνες ροές",
      description:
        "Αφαιρέστε επαναλαμβανόμενες εργασίες marketing με AI περιεχόμενο, ελέγχους ανταγωνισμού, chatbot απαντήσεις και αυτοματισμούς.",
      benefits: ["Ροές περιεχομένου", "API συνδέσεις", "Ανθρώπινος έλεγχος"],
      href: "/el/automation-2/",
    },
    {
      key: "reporting",
      title: "Αναφορές",
      eyebrow: "Καθαρά analytics",
      description:
        "Συγκεντρώστε στοιχεία marketing, SEO και πωλήσεων σε ένα καθαρό dashboard που ενημερώνεται αυτόματα.",
      benefits: ["KPI dashboards", "GA4 & GSC", "Executive summaries"],
      href: "/el/report-2/",
    },
    {
      key: "toolGeneration",
      title: "Δημιουργία Εργαλείων",
      eyebrow: "Προσαρμοσμένα συστήματα",
      description:
        "Δημιουργήστε custom SEO εργαλεία, εσωτερικά dashboards και data utilities όταν τα έτοιμα λογισμικά δεν ταιριάζουν.",
      benefits: ["Custom scripts", "Εσωτερικά εργαλεία", "Cloud integrations"],
      href: "/el/tool-generation-2/",
    },
  ],
};

export const servicesLanding = {
  en: {
    path: "/seo-marketing/",
    alternateHref: "/el/seo-marketing-2/",
    seoTitle: "SEO, AI and automation services | Freya SEO",
    metaDescription:
      "Explore Freya SEO services for AI SEO, automation, reporting and custom tool generation.",
    eyebrow: "Services",
    title: "SEO, AI and automation services built around your goals.",
    description:
      "We work on four things: getting you found, taking repetitive tasks off your team, making your data readable, and building tools you cannot buy off the shelf.",
    comparisonTitle: "How the services work together",
    comparisonText:
      "AI SEO creates the visibility plan, automation makes execution easier, reporting keeps everyone aligned, and custom tools close the gaps between platforms.",
    ctaTitle: "Ready to elevate your SEO marketing?",
    ctaText: "Tell us what is slowing growth down and we will point you to the right starting place.",
    ctaLabel: "Get in Touch",
  },
  el: {
    path: "/el/seo-marketing-2/",
    alternateHref: "/seo-marketing/",
    seoTitle: "Υπηρεσίες SEO, AI και αυτοματισμών | Freya SEO",
    metaDescription:
      "Δείτε τις υπηρεσίες Freya SEO για AI SEO, αυτοματισμούς, αναφορές και δημιουργία custom εργαλείων.",
    eyebrow: "Υπηρεσίες",
    title: "Υπηρεσίες SEO, AI και αυτοματισμών προσαρμοσμένες στους στόχους σας.",
    description:
      "Εστιάζουμε σε τέσσερα πράγματα: να σας βρίσκουν, να αφαιρούμε επαναλαμβανόμενες εργασίες, να κάνουμε τα δεδομένα κατανοητά και να χτίζουμε εργαλεία που δεν βρίσκονται έτοιμα.",
    comparisonTitle: "Πώς συνεργάζονται οι υπηρεσίες",
    comparisonText:
      "Το AI SEO δημιουργεί το πλάνο ορατότητας, οι αυτοματισμοί κάνουν την εκτέλεση πιο εύκολη, οι αναφορές κρατούν την ομάδα ευθυγραμμισμένη και τα custom εργαλεία κλείνουν τα κενά ανάμεσα στις πλατφόρμες.",
    ctaTitle: "Έτοιμοι να απογειώσετε το SEO Marketing σας;",
    ctaText: "Πείτε μας τι καθυστερεί την ανάπτυξη και θα σας δείξουμε το σωστό σημείο εκκίνησης.",
    ctaLabel: "Επικοινωνήστε",
  },
};

const enSharedProcess = [
  { title: "Discovery", text: "We map goals, markets, channels and the work that currently slows the team down." },
  { title: "Audit", text: "We inspect technical health, data quality, search demand and workflow gaps." },
  { title: "Strategy", text: "You get a practical roadmap with priorities, owners and measurable outcomes." },
  { title: "Implementation", text: "We build, optimize, connect and document the work in clean, usable steps." },
  { title: "Reporting", text: "Results are explained in dashboards and plain-language updates." },
  { title: "Optimisation", text: "We keep improving based on what the data and your team actually need next." },
];

const elSharedProcess = [
  { title: "Ανακάλυψη", text: "Χαρτογραφούμε στόχους, αγορές, κανάλια και όσα καθυστερούν σήμερα την ομάδα." },
  { title: "Έλεγχος", text: "Ελέγχουμε τεχνική υγεία, ποιότητα δεδομένων, ζήτηση αναζήτησης και κενά στη ροή εργασίας." },
  { title: "Στρατηγική", text: "Παραδίδουμε πρακτικό roadmap με προτεραιότητες, υπευθυνότητες και μετρήσιμα αποτελέσματα." },
  { title: "Υλοποίηση", text: "Χτίζουμε, βελτιστοποιούμε, συνδέουμε και τεκμηριώνουμε τη δουλειά σε καθαρά βήματα." },
  { title: "Αναφορά", text: "Τα αποτελέσματα εξηγούνται με dashboards και απλή γλώσσα." },
  { title: "Βελτιστοποίηση", text: "Συνεχίζουμε να βελτιώνουμε με βάση τα δεδομένα και τις πραγματικές ανάγκες της ομάδας." },
];

export const servicePages: Record<Locale, Record<ServiceKey, ServicePageData>> = {
  en: {
    aiSeo: {
      locale: "en",
      key: "aiSeo",
      slug: "ai-seo-2",
      href: "/ai-seo-2/",
      alternateHref: "/el/ai-seo-4/",
      eyebrow: "AI SEO",
      title: "Get found by Google, AI search and the customers ready to choose.",
      description:
        "Search is not just a Google box anymore. We help your brand become clear, useful and discoverable across classic search and AI answers.",
      heroMetrics: [
        { label: "SEO audit depth", value: 98, suffix: "%" },
        { label: "Keyword opportunities", value: 10000, suffix: "+" },
        { label: "Search surfaces", value: 4, suffix: "+" },
      ],
      overviewTitle: "AI SEO that still respects the fundamentals.",
      overviewText:
        "The strongest AI-search strategy starts with technical health, structured content and genuine expertise. We combine classic SEO with LLM/GEO optimisation so search engines and AI tools can understand why your business is the answer.",
      offers: [
        { title: "AI-assisted keyword research", text: "Topic clusters, intent mapping and opportunity scoring for organic and AI-led journeys." },
        { title: "Technical SEO auditing", text: "Indexing, crawlability, Core Web Vitals, structured data, redirects and internal linking." },
        { title: "AI-search visibility", text: "Content patterns that help ChatGPT, Gemini and answer engines understand your expertise." },
        { title: "Content opportunity discovery", text: "Briefs, outlines and page improvements grounded in demand, not guesswork." },
        { title: "Competitive research", text: "SERP, competitor and entity analysis so your strategy is built around the real landscape." },
        { title: "Measurement", text: "Reporting that connects rankings, visibility, traffic quality and conversion movement." },
      ],
      benefitsTitle: "Why AI SEO matters",
      benefitsIntro: "AI is changing how people discover businesses, but good strategy still rewards clarity, usefulness and trust.",
      benefits: [
        { title: "Organic traffic with intent", text: "Attract people already asking the questions your business can answer." },
        { title: "AI-search readiness", text: "Prepare your site to be understood by answer engines before competitors catch up." },
        { title: "Long-term authority", text: "Build topic depth that compounds instead of disappearing when ad spend pauses." },
        { title: "Smarter content decisions", text: "Prioritize pages and topics with evidence instead of publishing at random." },
      ],
      toolsTitle: "Tools we use for AI SEO",
      tools: toolList([
        "Google Search Console",
        "Google Analytics 4",
        "Ahrefs",
        "Semrush",
        "Screaming Frog",
        "ChatGPT",
        "Claude",
        "Gemini",
        "Google Trends",
        "BigQuery",
        "Python",
      ]),
      processTitle: "AI SEO process",
      process: enSharedProcess,
      dashboardTitle: "Visibility model",
      dashboardText: "A practical view of rankings, entity coverage, content gaps and AI-search mentions.",
      faqsTitle: "AI SEO FAQs",
      faqsIntro: "Clear answers about AI SEO, GEO, content quality and how classic SEO fits into the new search landscape.",
      faqs: [
        { question: "What exactly is AI SEO or GEO?", answer: "It is the work of helping AI systems find, understand and recommend your business, alongside classic SEO for Google." },
        { question: "Will this replace normal SEO?", answer: "No. It builds on the same fundamentals: technical health, useful content, authority and clear structure." },
        { question: "Do you guarantee first-page rankings?", answer: "No. We guarantee clear strategy, honest reporting and careful execution, not promises no one controls." },
        { question: "Can you work with our existing website?", answer: "Usually yes. Most sites need focused technical and content improvements rather than a full rebuild." },
      ],
      ctaTitle: "Curious where you actually stand?",
      ctaText: "Let’s look at your visibility across Google and AI search, then build a practical next step.",
      ctaLabel: "Get Your Free SEO Check",
    },
    automation: {
      locale: "en",
      key: "automation",
      slug: "automation",
      href: "/automation/",
      alternateHref: "/el/automation-2/",
      eyebrow: "Automation",
      title: "Let smart systems handle the repetitive work your team should not have to carry.",
      description:
        "We build AI-powered workflows for content, research, checks and handoffs so people can focus on judgment, creativity and customers.",
      heroMetrics: [
        { label: "Manual steps reduced", value: 42, suffix: "%" },
        { label: "Workflow templates", value: 18, suffix: "+" },
        { label: "Human review gates", value: 100, suffix: "%" },
      ],
      overviewTitle: "Automation that keeps humans in control.",
      overviewText:
        "The goal is not to replace your team. It is to remove repetitive tasks, standardize quality and make everyday marketing operations easier to run.",
      offers: [
        { title: "Content production automations", text: "Drafts, briefs, product descriptions, captions and email ideas prepared for review." },
        { title: "Competitor monitoring", text: "Repeatable checks for SERPs, offers, messaging and content movement." },
        { title: "Workflow integrations", text: "Connections between forms, docs, sheets, CRMs, schedulers and internal tools." },
        { title: "AI chatbot support", text: "Helpful assistant flows for FAQs, lead triage and internal knowledge." },
        { title: "Quality controls", text: "Human approval steps, tone rules and data checks built into every workflow." },
        { title: "Documentation", text: "Clear handover notes so your team understands what runs, where and why." },
      ],
      benefitsTitle: "Why automation matters",
      benefitsIntro: "Good automation gives time back without making the business feel less human.",
      benefits: [
        { title: "Fewer repetitive tasks", text: "Remove recurring work from the weekly to-do list." },
        { title: "Faster production", text: "Move from blank page to review-ready draft much faster." },
        { title: "Lower operational friction", text: "Connect tools that currently require copy-paste or manual checking." },
        { title: "Safer AI adoption", text: "Keep brand voice, privacy and review gates inside the workflow." },
      ],
      toolsTitle: "Tools we use for Automation",
      tools: toolList(["OpenAI API", "ChatGPT", "Claude", "Gemini", "Python", "Custom API Integrations"]),
      processTitle: "Automation process",
      process: enSharedProcess,
      dashboardTitle: "Workflow map",
      dashboardText: "A clean view of triggers, tasks, approval points and saved team time.",
      faqsTitle: "Automation FAQs",
      faqsIntro: "Answers about AI workflows, setup, data handling and where automation helps most.",
      faqs: [
        { question: "Will AI-generated content sound robotic?", answer: "Not when the workflow is built around your voice and includes a quick human review before publishing." },
        { question: "Do we need technical setup on our end?", answer: "Very little. We learn your tools, then handle the connections and documentation." },
        { question: "Can automations replace our content team?", answer: "They should not. Automations are best for drafts, checks and repetitive movement. Your team’s judgment stays essential." },
        { question: "Is our data safe?", answer: "We only connect approved tools and design workflows around the minimum data needed to complete the task." },
      ],
      ctaTitle: "Tell us what is eating your team’s time.",
      ctaText: "We will show you what can be automated safely and what should stay human.",
      ctaLabel: "Automate Something",
    },
    reporting: {
      locale: "en",
      key: "reporting",
      slug: "report",
      href: "/report/",
      alternateHref: "/el/report-2/",
      eyebrow: "Reporting",
      title: "One screen for the numbers that actually guide better decisions.",
      description:
        "We turn scattered SEO, marketing and sales data into dashboards and reports your team can understand without a spreadsheet headache.",
      heroMetrics: [
        { label: "Dashboard sources", value: 9, suffix: "+" },
        { label: "Manual exports cut", value: 80, suffix: "%" },
        { label: "KPI clarity", value: 100, suffix: "%" },
      ],
      overviewTitle: "Reporting that explains what changed and why it matters.",
      overviewText:
        "A useful report does more than collect numbers. It highlights movement, exposes problems early and makes the next decision easier.",
      offers: [
        { title: "Custom dashboards", text: "Looker Studio, Power BI or lightweight internal views tailored to your business." },
        { title: "KPI tracking", text: "Organic traffic, keyword visibility, leads, conversions and commercial performance." },
        { title: "Data consolidation", text: "GA4, Search Console, ad platforms, CRM exports, sheets and BigQuery." },
        { title: "Automated reporting", text: "Weekly or monthly summaries that reduce manual exports and screenshots." },
        { title: "Decision-ready insights", text: "Plain-language commentary that turns data into next actions." },
        { title: "Data quality checks", text: "Tracking gaps, duplicated metrics and reporting issues caught early." },
      ],
      benefitsTitle: "Why reporting matters",
      benefitsIntro: "When data is scattered, decisions slow down. Reporting brings the signal back into focus.",
      benefits: [
        { title: "One reliable view", text: "Stop jumping between platforms to understand performance." },
        { title: "Faster decisions", text: "Give teams and leadership the same source of truth." },
        { title: "Less manual work", text: "Reduce exports, screenshots and spreadsheet rebuilding." },
        { title: "Better accountability", text: "Connect SEO activity to the outcomes the business cares about." },
      ],
      toolsTitle: "Tools we use for Reporting",
      tools: toolList([
        "Looker Studio",
        "Power BI",
        "BigQuery",
        "SQL",
        "Python",
        "Google Analytics",
        "Google Search Console",
        "Google Sheets",
        "Custom API Integrations",
      ]),
      processTitle: "Reporting process",
      process: enSharedProcess,
      dashboardTitle: "Reporting dashboard",
      dashboardText: "A data model for traffic, rankings, leads, revenue signals and executive summaries.",
      faqsTitle: "Reporting FAQs",
      faqsIntro: "Answers about analytics setup, dashboard access, data sources and how reporting supports decisions.",
      faqs: [
        { question: "Do we need GA4 and Search Console already set up?", answer: "It helps, but it is not required. We can include setup or cleanup in the reporting work." },
        { question: "Can you include sales or CRM data?", answer: "Yes. We can connect marketing and sales data so the dashboard shows the full picture." },
        { question: "How often are dashboards updated?", answer: "That depends on the source. Many update daily or near real time without manual refreshes." },
        { question: "Can different team members see different views?", answer: "Yes. We can structure views for leadership, marketing and operations with different levels of detail." },
      ],
      ctaTitle: "Turn scattered marketing data into clear reports.",
      ctaText: "Build a reporting system that supports better decisions without manual chaos.",
      ctaLabel: "Build My Dashboard",
    },
    toolGeneration: {
      locale: "en",
      key: "toolGeneration",
      slug: "tool-generation",
      href: "/tool-generation/",
      alternateHref: "/el/tool-generation-2/",
      eyebrow: "Tool Generation",
      title: "Custom tools for workflows that off-the-shelf software cannot solve.",
      description:
        "We build focused internal tools, SEO utilities and API-connected systems around the way your business actually works.",
      heroMetrics: [
        { label: "Integration types", value: 8, suffix: "+" },
        { label: "Workflow fit", value: 100, suffix: "%" },
        { label: "Reusable utilities", value: 12, suffix: "+" },
      ],
      overviewTitle: "Software that fits the workflow, not the other way around.",
      overviewText:
        "Sometimes the right answer is a small internal dashboard, a data-cleaning utility, a custom script or an API-connected tool that removes a persistent bottleneck.",
      offers: [
        { title: "Custom internal tools", text: "Simple interfaces for teams that need repeatable workflows without complex software." },
        { title: "SEO utilities", text: "Keyword processors, metadata checkers, crawl review helpers and content QA tools." },
        { title: "Data-processing scripts", text: "Python and JavaScript utilities for cleaning, merging and transforming marketing data." },
        { title: "API-connected apps", text: "Tools that connect CRMs, ERPs, analytics platforms and internal data sources." },
        { title: "Workflow dashboards", text: "Operational views that show status, blockers, data health and next actions." },
        { title: "Cloud integrations", text: "Practical deployment and handover for tools your team can keep using." },
      ],
      benefitsTitle: "Why custom tools matter",
      benefitsIntro: "When the process is specific, the tool should be specific too.",
      benefits: [
        { title: "Built around real needs", text: "Solve the exact bottleneck instead of forcing work into a generic product." },
        { title: "Connected data flow", text: "Move information between systems that used to live in silos." },
        { title: "Fewer errors", text: "Replace copy-paste and fragile manual steps with repeatable logic." },
        { title: "Scalable operations", text: "Create tools that can grow with the business and be maintained cleanly." },
      ],
      toolsTitle: "Tools we use for Tool Generation",
      tools: toolList(["Python", "SQL", "JavaScript", "REST APIs", "Docker", "GitHub", "AWS", "Google Cloud"]),
      processTitle: "Tool generation process",
      process: enSharedProcess,
      dashboardTitle: "Build blueprint",
      dashboardText: "A view of inputs, APIs, processing steps, user roles and output states before build begins.",
      faqsTitle: "Tool Generation FAQs",
      faqsIntro: "Answers about custom tools, software ownership, integrations, maintenance and project scope.",
      faqs: [
        { question: "What if we do not know exactly what we need?", answer: "That is normal. We start by mapping the workflow and identifying the smallest useful tool." },
        { question: "Do you build from scratch or customize existing tools?", answer: "Both. The right route depends on scope, budget, maintenance and how unique the workflow is." },
        { question: "Who owns the software once it is built?", answer: "You do. The tool is built for your business and handed over clearly." },
        { question: "Do you offer ongoing maintenance?", answer: "Yes. We can maintain and improve the tool or hand it over with documentation." },
      ],
      ctaTitle: "Have a process that off-the-shelf software cannot solve?",
      ctaText: "Let’s build a tool around your workflow, your data and your team.",
      ctaLabel: "Start a Project",
    },
  },
  el: {
    aiSeo: {
      locale: "el",
      key: "aiSeo",
      slug: "ai-seo-4",
      href: "/el/ai-seo-4/",
      alternateHref: "/ai-seo-2/",
      eyebrow: "AI SEO",
      title: "Να σας βρίσκουν στη Google, στο AI search και οι πελάτες που είναι έτοιμοι να επιλέξουν.",
      description:
        "Η αναζήτηση δεν είναι πια μόνο ένα πεδίο Google. Βοηθάμε το brand σας να είναι καθαρό, χρήσιμο και ορατό σε κλασική αναζήτηση και AI απαντήσεις.",
      heroMetrics: [
        { label: "Βάθος SEO ελέγχου", value: 98, suffix: "%" },
        { label: "Ευκαιρίες λέξεων-κλειδιών", value: 10000, suffix: "+" },
        { label: "Κανάλια αναζήτησης", value: 4, suffix: "+" },
      ],
      overviewTitle: "AI SEO που στηρίζεται στα σωστά θεμέλια.",
      overviewText:
        "Η πιο δυνατή AI-search στρατηγική ξεκινά με τεχνική υγεία, δομημένο περιεχόμενο και πραγματική εξειδίκευση. Συνδυάζουμε κλασικό SEO με LLM/GEO optimization ώστε οι μηχανές και τα AI εργαλεία να κατανοούν γιατί είστε η σωστή απάντηση.",
      offers: [
        { title: "Έρευνα λέξεων-κλειδιών με AI", text: "Topic clusters, ανάλυση πρόθεσης και προτεραιοποίηση ευκαιριών." },
        { title: "Τεχνικός SEO έλεγχος", text: "Indexing, crawlability, Core Web Vitals, structured data, redirects και internal linking." },
        { title: "AI-search visibility", text: "Μοτίβα περιεχομένου που βοηθούν ChatGPT, Gemini και answer engines να κατανοήσουν την εξειδίκευσή σας." },
        { title: "Ευκαιρίες περιεχομένου", text: "Briefs, outlines και βελτιώσεις σελίδων βασισμένες σε πραγματική ζήτηση." },
        { title: "Ανάλυση ανταγωνισμού", text: "SERP, competitor και entity analysis για στρατηγική βασισμένη στο πραγματικό τοπίο." },
        { title: "Μέτρηση", text: "Αναφορές που συνδέουν rankings, visibility, ποιότητα traffic και conversions." },
      ],
      benefitsTitle: "Γιατί έχει σημασία το AI SEO",
      benefitsIntro: "Το AI αλλάζει τον τρόπο που οι άνθρωποι ανακαλύπτουν επιχειρήσεις, αλλά η καλή στρατηγική ακόμη ανταμείβει τη σαφήνεια, τη χρησιμότητα και την εμπιστοσύνη.",
      benefits: [
        { title: "Organic traffic με πρόθεση", text: "Προσελκύστε ανθρώπους που ήδη ρωτούν όσα μπορεί να απαντήσει η επιχείρησή σας." },
        { title: "Ετοιμότητα για AI search", text: "Προετοιμάστε το site σας να γίνεται κατανοητό από answer engines." },
        { title: "Μακροπρόθεσμη αυθεντία", text: "Χτίστε θεματικό βάθος που δεν εξαφανίζεται όταν σταματά η διαφήμιση." },
        { title: "Πιο έξυπνες αποφάσεις περιεχομένου", text: "Δώστε προτεραιότητα σε σελίδες και θέματα με δεδομένα." },
      ],
      toolsTitle: "Εργαλεία που χρησιμοποιούμε για AI SEO",
      tools: toolList([
        "Google Search Console",
        "Google Analytics 4",
        "Ahrefs",
        "Semrush",
        "Screaming Frog",
        "ChatGPT",
        "Claude",
        "Gemini",
        "Google Trends",
        "BigQuery",
        "Python",
      ]),
      processTitle: "Διαδικασία AI SEO",
      process: elSharedProcess,
      dashboardTitle: "Μοντέλο ορατότητας",
      dashboardText: "Πρακτική εικόνα για rankings, entity coverage, κενά περιεχομένου και AI-search mentions.",
      faqsTitle: "Συχνές ερωτήσεις AI SEO",
      faqsIntro: "Καθαρές απαντήσεις για AI SEO, GEO, ποιότητα περιεχομένου και τη σχέση με το κλασικό SEO.",
      faqs: [
        { question: "Τι είναι ακριβώς το AI SEO ή GEO;", answer: "Είναι η δουλειά που βοηθά AI συστήματα να βρίσκουν, να κατανοούν και να προτείνουν την επιχείρησή σας, παράλληλα με το κλασικό SEO." },
        { question: "Θα αντικαταστήσει το κανονικό SEO;", answer: "Όχι. Χτίζει πάνω στα ίδια θεμέλια: τεχνική υγεία, χρήσιμο περιεχόμενο, αυθεντία και καθαρή δομή." },
        { question: "Εγγυάστε πρώτη σελίδα;", answer: "Όχι. Εγγυόμαστε καθαρή στρατηγική, ειλικρινή αναφορά και προσεκτική εκτέλεση." },
        { question: "Μπορείτε να δουλέψετε με το υπάρχον site μας;", answer: "Συνήθως ναι. Τα περισσότερα sites χρειάζονται στοχευμένες τεχνικές και content βελτιώσεις, όχι πλήρη ανακατασκευή." },
      ],
      ctaTitle: "Θέλετε να δείτε πού πραγματικά βρίσκεστε;",
      ctaText: "Ας εξετάσουμε την ορατότητά σας σε Google και AI search και ας χτίσουμε το επόμενο πρακτικό βήμα.",
      ctaLabel: "Ζητήστε Δωρεάν SEO Έλεγχο",
    },
    automation: {
      locale: "el",
      key: "automation",
      slug: "automation-2",
      href: "/el/automation-2/",
      alternateHref: "/automation/",
      eyebrow: "Αυτοματισμοί",
      title: "Αφήστε τα έξυπνα συστήματα να χειριστούν την επαναλαμβανόμενη δουλειά.",
      description:
        "Χτίζουμε AI-powered workflows για περιεχόμενο, έρευνα, ελέγχους και handoffs, ώστε οι άνθρωποι να εστιάζουν στην κρίση, τη δημιουργικότητα και τους πελάτες.",
      heroMetrics: [
        { label: "Μείωση χειροκίνητων βημάτων", value: 42, suffix: "%" },
        { label: "Workflow templates", value: 18, suffix: "+" },
        { label: "Human review gates", value: 100, suffix: "%" },
      ],
      overviewTitle: "Αυτοματισμοί που κρατούν τον άνθρωπο στον έλεγχο.",
      overviewText:
        "Ο στόχος δεν είναι να αντικατασταθεί η ομάδα σας. Είναι να αφαιρεθούν επαναλαμβανόμενες εργασίες, να σταθεροποιηθεί η ποιότητα και να γίνει πιο εύκολη η καθημερινή λειτουργία marketing.",
      offers: [
        { title: "Αυτοματισμοί παραγωγής περιεχομένου", text: "Drafts, briefs, περιγραφές προϊόντων, captions και email ιδέες έτοιμες για έλεγχο." },
        { title: "Παρακολούθηση ανταγωνισμού", text: "Επαναλαμβανόμενοι έλεγχοι για SERPs, offers, messaging και content movement." },
        { title: "Workflow integrations", text: "Συνδέσεις ανάμεσα σε φόρμες, docs, sheets, CRMs, schedulers και εσωτερικά εργαλεία." },
        { title: "AI chatbot support", text: "Χρήσιμες ροές για FAQs, lead triage και internal knowledge." },
        { title: "Quality controls", text: "Human approvals, κανόνες tone of voice και data checks μέσα σε κάθε workflow." },
        { title: "Τεκμηρίωση", text: "Καθαρά handover notes ώστε η ομάδα να ξέρει τι τρέχει, πού και γιατί." },
      ],
      benefitsTitle: "Γιατί έχουν σημασία οι αυτοματισμοί",
      benefitsIntro: "Ο σωστός αυτοματισμός επιστρέφει χρόνο χωρίς να κάνει την επιχείρηση λιγότερο ανθρώπινη.",
      benefits: [
        { title: "Λιγότερες επαναλαμβανόμενες εργασίες", text: "Αφαιρέστε recurring tasks από το εβδομαδιαίο to-do." },
        { title: "Ταχύτερη παραγωγή", text: "Περάστε από λευκή σελίδα σε draft έτοιμο για review πιο γρήγορα." },
        { title: "Λιγότερη λειτουργική τριβή", text: "Συνδέστε εργαλεία που σήμερα απαιτούν copy-paste και χειροκίνητους ελέγχους." },
        { title: "Ασφαλέστερη χρήση AI", text: "Κρατήστε brand voice, privacy και review gates μέσα στη ροή." },
      ],
      toolsTitle: "Εργαλεία που χρησιμοποιούμε για αυτοματισμούς",
      tools: toolList(["OpenAI API", "ChatGPT", "Claude", "Gemini", "Python", "Custom API Integrations"]),
      processTitle: "Διαδικασία αυτοματισμών",
      process: elSharedProcess,
      dashboardTitle: "Χάρτης workflow",
      dashboardText: "Καθαρή εικόνα triggers, tasks, approval points και χρόνου που εξοικονομείται.",
      faqsTitle: "Συχνές ερωτήσεις αυτοματισμών",
      faqsIntro: "Απαντήσεις για AI workflows, setup, διαχείριση δεδομένων και τα σημεία όπου ο αυτοματισμός βοηθά περισσότερο.",
      faqs: [
        { question: "Θα ακούγεται ρομποτικό το AI περιεχόμενο;", answer: "Όχι όταν η ροή χτίζεται γύρω από τη φωνή σας και περιλαμβάνει ανθρώπινο review πριν τη δημοσίευση." },
        { question: "Χρειαζόμαστε τεχνικό setup;", answer: "Ελάχιστο. Μαθαίνουμε τα εργαλεία σας και αναλαμβάνουμε τις συνδέσεις και την τεκμηρίωση." },
        { question: "Μπορούν οι αυτοματισμοί να αντικαταστήσουν την content ομάδα;", answer: "Δεν πρέπει. Είναι καλύτεροι για drafts, checks και επαναλαμβανόμενη κίνηση. Η κρίση της ομάδας παραμένει απαραίτητη." },
        { question: "Είναι ασφαλή τα δεδομένα μας;", answer: "Συνδέουμε μόνο εγκεκριμένα εργαλεία και σχεδιάζουμε workflows με τα απολύτως απαραίτητα δεδομένα." },
      ],
      ctaTitle: "Πείτε μας τι τρώει χρόνο από την ομάδα σας.",
      ctaText: "Θα σας δείξουμε τι μπορεί να αυτοματοποιηθεί με ασφάλεια και τι πρέπει να μείνει ανθρώπινο.",
      ctaLabel: "Αυτοματοποιήστε κάτι",
    },
    reporting: {
      locale: "el",
      key: "reporting",
      slug: "report-2",
      href: "/el/report-2/",
      alternateHref: "/report/",
      eyebrow: "Αναφορές",
      title: "Μία οθόνη για τους αριθμούς που οδηγούν σε καλύτερες αποφάσεις.",
      description:
        "Μετατρέπουμε διάσπαρτα SEO, marketing και sales δεδομένα σε dashboards και αναφορές που η ομάδα καταλαβαίνει χωρίς πονοκέφαλο από spreadsheets.",
      heroMetrics: [
        { label: "Πηγές dashboard", value: 9, suffix: "+" },
        { label: "Μείωση manual exports", value: 80, suffix: "%" },
        { label: "Σαφήνεια KPIs", value: 100, suffix: "%" },
      ],
      overviewTitle: "Αναφορές που εξηγούν τι άλλαξε και γιατί έχει σημασία.",
      overviewText:
        "Μια χρήσιμη αναφορά δεν μαζεύει απλώς αριθμούς. Αναδεικνύει την κίνηση, εντοπίζει προβλήματα νωρίς και κάνει την επόμενη απόφαση πιο εύκολη.",
      offers: [
        { title: "Custom dashboards", text: "Looker Studio, Power BI ή lightweight internal views προσαρμοσμένα στην επιχείρησή σας." },
        { title: "KPI tracking", text: "Organic traffic, keyword visibility, leads, conversions και εμπορική απόδοση." },
        { title: "Συγκέντρωση δεδομένων", text: "GA4, Search Console, ad platforms, CRM exports, sheets και BigQuery." },
        { title: "Αυτόματες αναφορές", text: "Εβδομαδιαία ή μηνιαία summaries που μειώνουν exports και screenshots." },
        { title: "Decision-ready insights", text: "Σχόλια σε απλή γλώσσα που μετατρέπουν δεδομένα σε επόμενες ενέργειες." },
        { title: "Έλεγχοι ποιότητας δεδομένων", text: "Tracking gaps, διπλά metrics και reporting issues εντοπίζονται νωρίς." },
      ],
      benefitsTitle: "Γιατί έχουν σημασία οι αναφορές",
      benefitsIntro: "Όταν τα δεδομένα είναι διάσπαρτα, οι αποφάσεις αργούν. Οι αναφορές επαναφέρουν το σήμα στο προσκήνιο.",
      benefits: [
        { title: "Μία αξιόπιστη εικόνα", text: "Σταματήστε να πηδάτε από πλατφόρμα σε πλατφόρμα για να καταλάβετε την απόδοση." },
        { title: "Ταχύτερες αποφάσεις", text: "Δώστε στην ομάδα και στη διοίκηση την ίδια πηγή αλήθειας." },
        { title: "Λιγότερη χειροκίνητη δουλειά", text: "Μειώστε exports, screenshots και ξαναχτίσιμο spreadsheets." },
        { title: "Καλύτερη λογοδοσία", text: "Συνδέστε τη SEO δουλειά με τα αποτελέσματα που ενδιαφέρουν την επιχείρηση." },
      ],
      toolsTitle: "Εργαλεία που χρησιμοποιούμε για αναφορές",
      tools: toolList([
        "Looker Studio",
        "Power BI",
        "BigQuery",
        "SQL",
        "Python",
        "Google Analytics",
        "Google Search Console",
        "Google Sheets",
        "Custom API Integrations",
      ]),
      processTitle: "Διαδικασία αναφορών",
      process: elSharedProcess,
      dashboardTitle: "Reporting dashboard",
      dashboardText: "Data model για traffic, rankings, leads, revenue signals και executive summaries.",
      faqsTitle: "Συχνές ερωτήσεις αναφορών",
      faqsIntro: "Απαντήσεις για analytics setup, πρόσβαση dashboard, πηγές δεδομένων και πώς οι αναφορές στηρίζουν αποφάσεις.",
      faqs: [
        { question: "Χρειάζεται να έχουμε ήδη GA4 και Search Console;", answer: "Βοηθά, αλλά δεν είναι απαραίτητο. Μπορούμε να συμπεριλάβουμε setup ή cleanup στη δουλειά." },
        { question: "Μπορείτε να συμπεριλάβετε sales ή CRM δεδομένα;", answer: "Ναι. Μπορούμε να συνδέσουμε marketing και sales δεδομένα για πλήρη εικόνα." },
        { question: "Κάθε πότε ενημερώνονται τα dashboards;", answer: "Εξαρτάται από την πηγή. Πολλά ενημερώνονται καθημερινά ή σχεδόν real time χωρίς manual refresh." },
        { question: "Μπορούν διαφορετικά άτομα να βλέπουν διαφορετικές προβολές;", answer: "Ναι. Μπορούμε να δομήσουμε views για διοίκηση, marketing και operations." },
      ],
      ctaTitle: "Μετατρέψτε τα διάσπαρτα marketing δεδομένα σε σαφείς αναφορές.",
      ctaText: "Χτίστε reporting system που στηρίζει καλύτερες αποφάσεις χωρίς manual χάος.",
      ctaLabel: "Φτιάξτε το Dashboard μου",
    },
    toolGeneration: {
      locale: "el",
      key: "toolGeneration",
      slug: "tool-generation-2",
      href: "/el/tool-generation-2/",
      alternateHref: "/tool-generation/",
      eyebrow: "Δημιουργία Εργαλείων",
      title: "Custom εργαλεία για workflows που τα έτοιμα λογισμικά δεν μπορούν να λύσουν.",
      description:
        "Χτίζουμε εστιασμένα internal tools, SEO utilities και API-connected συστήματα γύρω από τον τρόπο που λειτουργεί πραγματικά η επιχείρησή σας.",
      heroMetrics: [
        { label: "Τύποι integrations", value: 8, suffix: "+" },
        { label: "Προσαρμογή στη ροή", value: 100, suffix: "%" },
        { label: "Reusable utilities", value: 12, suffix: "+" },
      ],
      overviewTitle: "Λογισμικό που ταιριάζει στη ροή εργασίας, όχι το αντίστροφο.",
      overviewText:
        "Μερικές φορές η σωστή λύση είναι ένα μικρό εσωτερικό dashboard, ένα data-cleaning utility, ένα custom script ή ένα API-connected εργαλείο που αφαιρεί ένα μόνιμο bottleneck.",
      offers: [
        { title: "Custom internal tools", text: "Απλά interfaces για ομάδες που χρειάζονται επαναλαμβανόμενες ροές χωρίς πολύπλοκο λογισμικό." },
        { title: "SEO utilities", text: "Keyword processors, metadata checkers, crawl review helpers και content QA tools." },
        { title: "Data-processing scripts", text: "Python και JavaScript utilities για καθαρισμό, συγχώνευση και μετατροπή marketing δεδομένων." },
        { title: "API-connected apps", text: "Εργαλεία που συνδέουν CRMs, ERPs, analytics platforms και internal data sources." },
        { title: "Workflow dashboards", text: "Operational views για status, blockers, data health και next actions." },
        { title: "Cloud integrations", text: "Πρακτικό deployment και handover για εργαλεία που η ομάδα μπορεί να συνεχίσει να χρησιμοποιεί." },
      ],
      benefitsTitle: "Γιατί έχουν σημασία τα custom εργαλεία",
      benefitsIntro: "Όταν η διαδικασία είναι συγκεκριμένη, το εργαλείο πρέπει να είναι συγκεκριμένο.",
      benefits: [
        { title: "Χτισμένα γύρω από πραγματικές ανάγκες", text: "Λύστε το ακριβές bottleneck αντί να πιέζετε τη δουλειά σε generic προϊόν." },
        { title: "Συνδεδεμένη ροή δεδομένων", text: "Μετακινήστε πληροφορίες ανάμεσα σε συστήματα που λειτουργούσαν σε silos." },
        { title: "Λιγότερα λάθη", text: "Αντικαταστήστε copy-paste και εύθραυστα manual βήματα με repeatable logic." },
        { title: "Scalable operations", text: "Δημιουργήστε εργαλεία που μεγαλώνουν με την επιχείρηση και συντηρούνται καθαρά." },
      ],
      toolsTitle: "Εργαλεία που χρησιμοποιούμε για τη δημιουργία εργαλείων",
      tools: toolList(["Python", "SQL", "JavaScript", "REST APIs", "Docker", "GitHub", "AWS", "Google Cloud"]),
      processTitle: "Διαδικασία δημιουργίας εργαλείων",
      process: elSharedProcess,
      dashboardTitle: "Build blueprint",
      dashboardText: "Εικόνα inputs, APIs, processing steps, user roles και output states πριν ξεκινήσει το build.",
      faqsTitle: "Συχνές ερωτήσεις δημιουργίας εργαλείων",
      faqsIntro: "Απαντήσεις για custom tools, ιδιοκτησία λογισμικού, integrations, συντήρηση και scope έργου.",
      faqs: [
        { question: "Κι αν δεν ξέρουμε ακριβώς τι χρειαζόμαστε;", answer: "Είναι φυσιολογικό. Ξεκινάμε χαρτογραφώντας τη ροή και εντοπίζοντας το μικρότερο χρήσιμο εργαλείο." },
        { question: "Χτίζετε από το μηδέν ή προσαρμόζετε υπάρχοντα εργαλεία;", answer: "Και τα δύο. Η σωστή επιλογή εξαρτάται από scope, budget, maintenance και τη μοναδικότητα της ροής." },
        { question: "Ποιος έχει την ιδιοκτησία του software;", answer: "Εσείς. Το εργαλείο χτίζεται για την επιχείρησή σας και παραδίδεται καθαρά." },
        { question: "Προσφέρετε συντήρηση μετά το launch;", answer: "Ναι. Μπορούμε να συντηρούμε και να βελτιώνουμε το εργαλείο ή να το παραδώσουμε με τεκμηρίωση." },
      ],
      ctaTitle: "Έχετε μια διαδικασία που δεν μπορεί να καλύψει ένα έτοιμο λογισμικό;",
      ctaText: "Ας δημιουργήσουμε ένα εργαλείο προσαρμοσμένο στη ροή εργασίας, τα δεδομένα και την ομάδα σας.",
      ctaLabel: "Ξεκινήστε ένα Project",
    },
  },
};

export function getServicePage(locale: Locale, key: ServiceKey) {
  return servicePages[locale][key];
}

export function getServiceSummaries(locale: Locale) {
  return serviceSummaries[locale];
}
