export const commonEn = {
  locale: "en",
  skipToContent: "Skip to content",
  language: {
    label: "Language",
    current: "English",
    alternate: "Ελληνικά",
  },
  actions: {
    primaryCta: "Let’s Work Together",
    exploreServices: "Explore Services",
    viewCertificate: "View Certificate",
    readArticle: "Read Article",
    backToTop: "Back to top",
    openMenu: "Open navigation menu",
    closeMenu: "Close navigation menu",
    openServices: "Open services menu",
    closeServices: "Close services menu",
    search: "Search",
    loadMore: "Load more",
  },
  breadcrumbs: {
    home: "Home",
    services: "Services",
    blog: "Blog",
  },
  footer: {
    description:
      "Freya SEO combines technical SEO, AI-assisted analysis, automation and clear reporting for businesses that want organic growth without the fog.",
    services: "Services",
    usefulLinks: "Useful Links",
    contact: "Contact",
    certificates: "Certificates",
    about: "About",
    privacy: "Privacy Policy",
    terms: "Terms of Use",
    copyright: "Freya SEO. All rights reserved.",
    response: "Replies within one business day.",
  },
  contact: {
    heroEyebrow: "Free SEO consultation",
    title: "Let’s get your business found in the places your customers search.",
    text: "Tell us a bit about your business, your website and what feels stuck. You will get a thoughtful reply within one business day.",
    responseTime: "Expected response time: one business day",
    infoTitle: "Prefer email?",
    infoText: "Reach us directly at pavlinahormann@gmail.com.",
    formTitle: "Start the conversation",
    labels: {
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email Address",
      company: "Company",
      service: "Service",
      budget: "Budget",
      message: "Message",
      submit: "Submit",
    },
    services: ["AI SEO", "Automation", "Reporting", "Tool Generation"],
    budgets: ["Not sure yet", "Under €2,000", "€2,000 - €5,000", "€5,000+"],
    errors: {
      required: "This field is required.",
      email: "Please enter a valid email address.",
    },
    success: "Thank you. Your message is ready for the future backend integration.",
  },
};
